apiVersion: apps/v1
kind: Deployment
metadata:
  name: contentmgr
  labels:
    app: contentmgr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contentmgr
  template:
    metadata:
      labels:
        app: contentmgr
    spec:
      containers:
      - name: contentmgr
        image: contentmgr:{{ .Commit }}
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: contentmgr
spec:
  selector:
    app: contentmgr
  ports:
  - protocol: TCP
    port: 2018
    targetPort: {{ .Port }}
